### ISSUE TITLE
Remove nmap from dependencies

### ISSUE THREAD

**Issue by deemru** [mtrojnar/stunnel#4]
Hello, @mtrojnar, what is the point of using `nmap` in `.travis.yml`?

We just got `potential abuse` from @travis-ci because of `nmap`:
>This is a part of our abuse prevention system, which blocks a repo if it looks like someone is trying to use a network scanning tool or p2p application. It's not a very sophisticated check, so often we have false positives. Could I ask how you're using Travis for this repository, and how you're using nmap in relation to Travis?

And after removing nmap:
>After review, and since you have removed nmap from your .travis.yml file, we've proceeded with unflagging your account. You'll need to remove nmap from other branches as well to not be detected again. Sorry for the inconvenience.

<br/>

Please consider removing `nmap` from dependencies.

**Comment by mtrojnar** [comment]
Yes, this is indeed a false positive.  The "nmap" package includes the "ncat" tools, which is used for the "make check" target.
