### ISSUE TITLE
503 responses

### ISSUE THREAD

**Issue by fzonneveld** [mtrojnar/stunnel#6]
### setup
My setup is apache-benchmark (ab) <-> stunnel <->  haproxy.

Stunnel from source, v5.49.
Stunnel config is using 'cert' option to enforce client authentication.

### Problem description
When I run ab in concurrent mode (-c 4 for exampel), everything is fine.
When I run ab (-c 4) for the second time I see stunnel sometimes trying to reuse connections, but this always results in a SSL error in haproxy, returning a 503.  The log file contains '2019.02.28 12:40:13 LOG6[7]: TLS connected: previous session reused'.

### Trials
When I disable caching for the client (not server) in src/ctx.c:224,  SSL_CTX_set_session_cache_mode function SSL_SESS_CACHE_BOTH to SSL_SESS_CACHE_SERVER, everything goes fine.

What is also strange to me is that 'previous session reused' is not happening always, but seems to have some random behavior.

I did not try this out with only server authentication configured in stunnel.conf, but I assume it will work fine, because this is actually what is enabled when I do SSL_SESS_CACHE_SERVER only.

Also tried the latest v5.50, same issue.

Thanks Frank,

**Comment by mtrojnar** [comment]
Can you please include your stunnel.conf?

**Comment by fzonneveld** [comment]
Sorry for long time, busy. We have resolved the issue by disabling all the TLS caching support on the server site including tickets. I think it has to do with an issue with the haproxy config. Will close the issue becuase I think it is not reletated to stunnel. Thanks for support.
